apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: users-secret                   
  namespace: applications                 
spec:
  provider: aws                           
  parameters:                             
    objects: |
      - objectName: "users"
        objectType: "secretsmanager"